Shreya/snorfle
teamresistance/fist-of-life pull request #2
Opened 2016-12-23 16:51 UTC by ShreyaRavi

🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧 
This is just a start to the snorfle subsystem being implemented. This is very much under construction right now, if you couldn't tell by the construction signs. However, feel free to roast it and I'll make changed accordingly.
 🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧🚧

2016-12-23 16:55 UTC, ShreyaRavi commented
So i didn't do this using the Teleop and Auto delegates, so there's a conflict in the Robot class, which I will take care of in a later commit.

2016-12-31 15:26 UTC, rothso requested changes
This code is super solid, really nicely done.
* I was initially a skeptic about using inheritance for code reuse but your use with `Snorfle` proved to me it can be powerful when done properly.
* The consistent ordering of the rollers and spinners is great.

Immaculate adherence to the code style too. My only ~~suggestion~~ 🔥  has to do with scoping: we probably want to hide the base `Snorfle` command from the world and only expose its subclasses, which calls for moving these commands into their own package and restricting how `Snorfle` can be accessed.

PS: We need a command to stop the Snorfler too, right?

2016-12-31 15:26 UTC, rothso commented on src/main/java/org/teamresistance/frc/Snorfle.java
> +public class Snorfle extends Command {
I see it's being used as a base class―smart―thoughts about making this `abstract` to prevent direct instantiation?

2016-12-31 15:26 UTC, rothso commented on src/main/java/org/teamresistance/frc/Snorfle.java
> +  double spinnerSpeed;
For good measure, these fields should be `private final`. It's clear they only are used internally, so other classes shouldn't have the need to access them. They're also never reassigned, so it's a good idea to keep enforcing that.

+1 for embracing immutability with your design here.

2016-12-31 15:26 UTC, rothso commented on src/main/java/org/teamresistance/frc/Snorfle.java
> +public class Snorfle extends Command {
Now is also a good time to start packaging things up―could you move the Snorfler commands into a dedicated package? You may also want to then consider making this class `protected` to keep it self-contained.

2016-12-31 15:26 UTC, rothso commented on src/main/java/org/teamresistance/frc/Snorfle.java
> +  public Snorfle(Motor rollers, Motor spinners, double rollerSpeed, double spinnerSpeed) {
You probably want this constructor to be `protected` to prevent it from coming up as an option when instantiating any of its subclasses.

2016-12-31 15:26 UTC, rothso commented on src/main/java/org/teamresistance/frc/SnorfleIn.java
> +import com.sun.xml.internal.bind.v2.runtime.reflect.opt.Const;
Looks like IntelliJ snuck in these unwarranted imports, lol.

2016-12-31 15:26 UTC, rothso commented on src/main/java/org/teamresistance/frc/Constants.java
> +
No space here. 🙂

2017-01-01 02:47 UTC, rothso commented on src/main/java/org/teamresistance/frc/Snorfle.java
> +public class Snorfle extends Command {
On this note: I'd probably move all Snorfler-related stuff (commands included) to the `subsystem.snorfle` package, similar to how it's done in #4. I had tried the `commands` package approach but didn't like it, it makes scopes messy.

2017-01-26 03:55 UTC, rothso commented
Closing for a lack of relevance, *au revoir*.

2017-01-26 03:55 UTC, closed without merging